variables:
  APP_NAME: $CI_PROJECT_NAME

stages:
  - test

postman-tests:
  stage: test
  image: postman/newman
  script:
    - echo "Running Postman tests"
    - newman run biosamples-api-tests.postman_collection.json --environment wwwint.postman_environment.json --env-var "WEBIN_USER=$WEBIN_USER" --env-var "WEBIN_PASS=$WEBIN_PASS"
  only:
    - main

