variables:
  APP_NAME: $CI_PROJECT_NAME

stages:
  - test

postman-tests-all:
  stage: test
  image:
    name: postman/newman
    entrypoint: [ "/bin/sh", "-c" ]
  script:
    - newman --version
    - newman run biosamples-api-tests.postman_collection.json --environment wwwint.postman_environment.json --env-var "WEBIN_USER=$WEBIN_USER" --env-var "vault:WEBIN_PASS=$WEBIN_PASS"  --reporters cli,junit,html --reporter-junit-export newman-report.xml --reporter-html-export newman-report.html
  rules:
    - if: '$TRIGGER_SERVICE == "false" || $CI_COMMIT_BRANCH == "main"'
  artifacts:
    when: always
    reports:
      junit: newman-report.xml
    paths:
      - newman-report.html
    expire_in: 7 days

postman-test-service:
  stage: test
  image:
    name: postman/newman
    entrypoint: [ "/bin/sh", "-c" ]
  script:
    - echo "$FOLDER"
    - echo "$BSD_ENV".postman_environment.json
    - |
       newman run biosamples-api-tests.postman_collection.json \
       --environment "$BSD_ENV".postman_environment.json \
       --env-var "WEBIN_USER=$WEBIN_USER" \
       --env-var "WEBIN_PASS=$WEBIN_PASS" \
       --folder "$FOLDER"
  rules:
    - if: '$TRIGGER_SERVICE == "true"'

